### ISSUE TITLE
Production errors: REDCap AE Survey Link

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/coach#157]
Over the last 7 days, we've gotten an error similar to this 5 times:

`2024-01-12 09:05:13.835 [http-nio-50000-exec-5] ERROR e.o.c.c.controller.HomeController [HomeController.java:121] caught edu.ohsu.cmp.coach.exception.REDCapException building home page
edu.ohsu.cmp.coach.exception.REDCapException: 400 BAD_REQUEST "COACH is temporarily unavailable. Please try again later."
        at edu.ohsu.cmp.coach.service.REDCapService.checkException(REDCapService.java:336)
        at edu.ohsu.cmp.coach.service.REDCapService.getAESurveyLinkForRepeatInstance(REDCapService.java:328)
        at edu.ohsu.cmp.coach.service.REDCapService.getAESurveyLink(REDCapService.java:302)
        at edu.ohsu.cmp.coach.controller.HomeController.view(HomeController.java:101)
        at jdk.internal.reflect.GeneratedMethodAccessor165.invoke(Unknown Source)`

The steps that would make this happen:

- Participant logs in through MyChart. Their record is checked in REDCap to make sure they are active, and then they are forwarded to the home page.
- In order for COACH to load the home page, REDCap is queried again to determine the survey link to provide the participants for reporting AEs. REDCap returns a "400" response, which is *usually* how REDCap reports it is down for upgrades. But it is unlikely that it's actually down since it would have been queried earlier in the SessionController to even get to this point. I'm not clear what the participant sees, but it's not a nice error message or good experience.

I'm going to add some additional logging of the REDCap response to hopefully understand what is going on. I'll also simply hide the AE survey link in this instance so the rest of the method can proceed and the home page can be loaded.

**Comment by aeyates** [comment]
Through local testing, I was able to confirm the participant experience. Part of the page still loaded (the graph and traffic light), but no recommendations came through because the exception thrown prevented several pieces of the page from being built. I moved the request for the AE link to the bottom of the method so that the rest of the page will load fine and only the message about how to report an AE will be missing. There is also additional logging now, so we should be able to see the response body coming from REDCap to understand what might be occurring.
