### ISSUE TITLE
OutOfMemoryError - backend sessions appear to not be expiring correctly

### ISSUE THREAD

**Issue by mattStorer** [OHSUCMP/coach#217]
While investigating an issue with COACH whereby the system experienced an _OutOfMemoryError_, I see there are many logs relating to refreshing Omron tokens for sessions that should not exist for such a long period of time.

```
2024-07-28 06:45:29.581 [http-nio-50000-exec-22] ERROR e.o.cmp.coach.GlobalExceptionHandler [GlobalExceptionHandler.java:26] trapped exception org.springframework.web.util.NestedServletException at /recommendation for session B7A8BDA7C226236B6FAAC54A3CD92078 - Async processing failed; nested exception is java.lang.OutOfMemoryError: Java heap space
org.springframework.web.util.NestedServletException: Async processing failed; nested exception is java.lang.OutOfMemoryError: Java heap space
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod$ConcurrentResultHandlerMethod.lambda$new$0(ServletInvocableHandlerMethod.java:223)
        at java.base/jdk.internal.reflect.GeneratedMethodAccessor171.invoke(Unknown Source)

[...]

Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.base/java.nio.HeapCharBuffer.<init>(HeapCharBuffer.java:61)
        at java.base/java.nio.CharBuffer.allocate(CharBuffer.java:348)
        at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:792)
        at java.base/java.nio.charset.Charset.decode(Charset.java:814)
        at edu.ohsu.cmp.coach.model.cqfruler.HookRequest.sanitize(HookRequest.java:114)
        at edu.ohsu.cmp.coach.model.cqfruler.HookRequest.<init>(HookRequest.java:63)
        at edu.ohsu.cmp.coach.model.cqfruler.HookRequest.<init>(HookRequest.java:36)
        at edu.ohsu.cmp.coach.service.RecommendationService.getCards(RecommendationService.java:150)
        at edu.ohsu.cmp.coach.workspace.UserWorkspace$15.apply(UserWorkspace.java:601)
        at edu.ohsu.cmp.coach.workspace.UserWorkspace$15.apply(UserWorkspace.java:593)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$13(BoundedLocalCache.java:2511)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$1384/0x0000000840a38c40.apply(Unknown Source)
        at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2509)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2492)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:111)
        at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
        at edu.ohsu.cmp.coach.workspace.UserWorkspace.getCards(UserWorkspace.java:593)
        at edu.ohsu.cmp.coach.controller.HomeController$1.call(HomeController.java:235)
        at edu.ohsu.cmp.coach.controller.HomeController$1.call(HomeController.java:230)
```

For example, `storer@coach-virt ~/coach/log/archive/2024 $ grep -r -i 'scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34' * | less` returns the following:

```
07/coach.2024-07-12.log:2024-07-12 07:57:00.917 [http-nio-50000-exec-2] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Sat Jul 13 07:56:50 PDT 2024
07/coach.2024-07-12.log:2024-07-12 07:57:28.137 [http-nio-50000-exec-11] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Sat Jul 13 07:57:18 PDT 2024
07/coach.2024-07-13.log:2024-07-13 07:56:51.208 [quartzScheduler_Worker-10] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Sun Jul 14 07:56:41 PDT 2024
07/coach.2024-07-13.log:2024-07-13 07:57:18.487 [quartzScheduler_Worker-1] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Sun Jul 14 07:57:08 PDT 2024
07/coach.2024-07-14.log:2024-07-14 07:56:41.516 [quartzScheduler_Worker-2] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Mon Jul 15 07:56:31 PDT 2024
07/coach.2024-07-14.log:2024-07-14 07:57:08.796 [quartzScheduler_Worker-3] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Mon Jul 15 07:56:58 PDT 2024
07/coach.2024-07-15.log:2024-07-15 07:56:31.885 [quartzScheduler_Worker-8] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Tue Jul 16 07:56:21 PDT 2024
07/coach.2024-07-15.log:2024-07-15 07:56:59.098 [quartzScheduler_Worker-9] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Tue Jul 16 07:56:49 PDT 2024
07/coach.2024-07-16.log:2024-07-16 07:56:22.283 [quartzScheduler_Worker-2] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Wed Jul 17 07:56:12 PDT 2024
07/coach.2024-07-16.log:2024-07-16 07:56:49.399 [quartzScheduler_Worker-3] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Wed Jul 17 07:56:39 PDT 2024
07/coach.2024-07-17.log:2024-07-17 07:56:12.612 [quartzScheduler_Worker-2] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Thu Jul 18 07:56:02 PDT 2024
07/coach.2024-07-17.log:2024-07-17 07:56:39.726 [quartzScheduler_Worker-3] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Thu Jul 18 07:56:29 PDT 2024
07/coach.2024-07-18.log:2024-07-18 07:56:03.055 [quartzScheduler_Worker-1] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Fri Jul 19 07:55:53 PDT 2024
07/coach.2024-07-18.log:2024-07-18 07:56:30.114 [quartzScheduler_Worker-2] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Fri Jul 19 07:56:20 PDT 2024
07/coach.2024-07-19.log:2024-07-19 07:55:53.422 [quartzScheduler_Worker-9] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Sat Jul 20 07:55:43 PDT 2024
07/coach.2024-07-19.log:2024-07-19 07:56:20.459 [quartzScheduler_Worker-10] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Sat Jul 20 07:56:10 PDT 2024
07/coach.2024-07-20.log:2024-07-20 07:55:43.799 [quartzScheduler_Worker-8] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Sun Jul 21 07:55:33 PDT 2024
07/coach.2024-07-20.log:2024-07-20 07:56:10.790 [quartzScheduler_Worker-9] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Sun Jul 21 07:56:00 PDT 2024
07/coach.2024-07-21.log:2024-07-21 07:55:34.193 [quartzScheduler_Worker-7] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Mon Jul 22 07:55:24 PDT 2024
07/coach.2024-07-21.log:2024-07-21 07:56:01.179 [quartzScheduler_Worker-8] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Mon Jul 22 07:55:51 PDT 2024
07/coach.2024-07-22.log:2024-07-22 07:55:24.562 [quartzScheduler_Worker-5] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Tue Jul 23 07:55:14 PDT 2024
07/coach.2024-07-22.log:2024-07-22 07:55:51.529 [quartzScheduler_Worker-6] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Tue Jul 23 07:55:41 PDT 2024
07/coach.2024-07-23.log:2024-07-23 07:55:14.931 [quartzScheduler_Worker-8] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Wed Jul 24 07:55:04 PDT 2024
07/coach.2024-07-23.log:2024-07-23 07:55:41.872 [quartzScheduler_Worker-9] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Wed Jul 24 07:55:31 PDT 2024
07/coach.2024-07-24.log:2024-07-24 07:55:05.408 [quartzScheduler_Worker-3] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Thu Jul 25 07:54:55 PDT 2024
07/coach.2024-07-24.log:2024-07-24 07:55:32.199 [quartzScheduler_Worker-4] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Thu Jul 25 07:55:22 PDT 2024
07/coach.2024-07-25.log:2024-07-25 07:54:55.774 [quartzScheduler_Worker-5] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Fri Jul 26 07:54:45 PDT 2024
07/coach.2024-07-25.log:2024-07-25 07:55:22.559 [quartzScheduler_Worker-6] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Fri Jul 26 07:55:12 PDT 2024
07/coach.2024-07-26.log:2024-07-26 07:54:46.201 [quartzScheduler_Worker-7] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Sat Jul 27 07:54:36 PDT 2024
07/coach.2024-07-26.log:2024-07-26 07:55:12.903 [quartzScheduler_Worker-8] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Sat Jul 27 07:55:02 PDT 2024
07/coach.2024-07-27.log:2024-07-27 07:54:36.526 [quartzScheduler_Worker-8] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Sun Jul 28 07:54:26 PDT 2024
07/coach.2024-07-27.log:2024-07-27 07:55:03.240 [quartzScheduler_Worker-9] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Sun Jul 28 07:54:53 PDT 2024
07/coach.2024-07-28.log:2024-07-28 07:54:26.869 [quartzScheduler_Worker-7] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Mon Jul 29 07:54:16 PDT 2024
07/coach.2024-07-28.log:2024-07-28 07:54:53.568 [quartzScheduler_Worker-8] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Mon Jul 29 07:54:43 PDT 2024
07/coach.2024-07-29.log:2024-07-29 07:54:17.274 [quartzScheduler_Worker-7] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Tue Jul 30 07:54:07 PDT 2024
07/coach.2024-07-29.log:2024-07-29 07:54:43.912 [quartzScheduler_Worker-8] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session E05FE21C15752BD15F07A79A3951DB34 at Tue Jul 30 07:54:33 PDT 2024
```

Why does session `E05FE21C15752BD15F07A79A3951DB34 ` persist for more than two weeks?

Omron token refresh jobs are designed to schedule additional refresh token jobs, so long as the associated _UserWorkspace_ object continues to exist, associated with the specified _sessionId_ value.

After the experienced _OutOfMemoryError_ on 2024-07-28, logs appear to only include Omron token refresh logs.  Take, for example, these logs from 2024-07-29:

```
2024-07-29 04:24:02.196 [quartzScheduler_Worker-5] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-af91329f-841c-4831-b29c-434876113712 fired at Mon Jul 29 04:24:02 PDT 2024
2024-07-29 04:24:02.625 [quartzScheduler_Worker-5] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session 9B52ABECFF4DF1CC43B30791874B099C at Tue Jul 30 04:23:52 PDT 2024
2024-07-29 04:28:55.993 [quartzScheduler_Worker-6] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-fc0754cd-47d4-4653-ad59-9b5e0443e97d fired at Mon Jul 29 04:28:55 PDT 2024
2024-07-29 04:28:56.466 [quartzScheduler_Worker-6] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session 4A328BD02DFA5E08F94B6774AED68811 at Tue Jul 30 04:28:46 PDT 2024
2024-07-29 04:55:32.694 [quartzScheduler_Worker-7] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-99ef952e-ffd3-4fef-9bfd-2841b8385c60 fired at Mon Jul 29 04:55:32 PDT 2024
2024-07-29 04:55:33.111 [quartzScheduler_Worker-7] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session 3AD7E96082372EA4219D8C11C1BE22F3 at Tue Jul 30 04:55:23 PDT 2024
2024-07-29 04:57:52.293 [quartzScheduler_Worker-8] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-4beee04a-1d39-46ad-872d-f3e12c465ea1 fired at Mon Jul 29 04:57:52 PDT 2024
2024-07-29 04:57:52.681 [quartzScheduler_Worker-8] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session 85444ABA117D70BF509F457B5231DCBB at Tue Jul 30 04:57:42 PDT 2024
2024-07-29 06:13:29.156 [quartzScheduler_Worker-9] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-a7d258c7-26a9-442f-a0a2-aa6676f3d6ce fired at Mon Jul 29 06:13:29 PDT 2024
2024-07-29 06:13:29.639 [quartzScheduler_Worker-9] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session 2E276B562C5FCA7C7F5D72B87186DE09 at Tue Jul 30 06:13:19 PDT 2024
2024-07-29 06:14:44.855 [quartzScheduler_Worker-10] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-9590dc7c-91dd-40a6-995b-190382a5b41f fired at Mon Jul 29 06:14:44 PDT 2024
2024-07-29 06:14:45.260 [quartzScheduler_Worker-10] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session 4EEAA7A3FA880334CE82DBCB9357C921 at Tue Jul 30 06:14:35 PDT 2024
2024-07-29 06:15:11.834 [quartzScheduler_Worker-1] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-84151d0a-b8f0-402b-8cd3-17773956eeda fired at Mon Jul 29 06:15:11 PDT 2024
2024-07-29 06:15:12.217 [quartzScheduler_Worker-1] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session 4EEAA7A3FA880334CE82DBCB9357C921 at Tue Jul 30 06:15:02 PDT 2024
2024-07-29 06:16:02.375 [quartzScheduler_Worker-3] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-8c8c90e7-dafe-4b0c-b596-069845b293e6 fired at Mon Jul 29 06:16:02 PDT 2024
2024-07-29 06:16:05.051 [quartzScheduler_Worker-3] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session 2E276B562C5FCA7C7F5D72B87186DE09 at Tue Jul 30 06:15:55 PDT 2024
2024-07-29 06:18:07.736 [quartzScheduler_Worker-2] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-1adc4eeb-430e-47cb-ae20-0a8b333111b3 fired at Mon Jul 29 06:18:07 PDT 2024
2024-07-29 06:18:08.208 [quartzScheduler_Worker-2] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session EED7913E13502ABE6024D1C078DEC12D at Tue Jul 30 06:17:58 PDT 2024
2024-07-29 06:20:49.057 [quartzScheduler_Worker-4] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-99a89d55-1c42-45b6-a661-73d752537dfb fired at Mon Jul 29 06:20:49 PDT 2024
2024-07-29 06:20:49.487 [quartzScheduler_Worker-4] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session C2B7B812FA7BBD1BDB7C82466CE055D7 at Tue Jul 30 06:20:39 PDT 2024
2024-07-29 06:22:45.529 [quartzScheduler_Worker-5] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-469efcae-5d8e-4564-ab0c-bd77a2140501 fired at Mon Jul 29 06:22:45 PDT 2024
2024-07-29 06:22:45.883 [quartzScheduler_Worker-5] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session C8571B1B432D456231AED0F7387C7CAC at Tue Jul 30 06:22:35 PDT 2024
2024-07-29 06:23:53.170 [quartzScheduler_Worker-6] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-8370fd28-f2d4-418c-a733-2496ae00b30d fired at Mon Jul 29 06:23:53 PDT 2024
2024-07-29 06:23:53.530 [quartzScheduler_Worker-6] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session BDFD972DF69C39A1310EA1EB328DDCCB at Tue Jul 30 06:23:43 PDT 2024
2024-07-29 06:25:15.471 [quartzScheduler_Worker-7] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-023b3447-b9f1-4b07-bb0c-5bb53b92c103 fired at Mon Jul 29 06:25:15 PDT 2024
2024-07-29 06:25:15.829 [quartzScheduler_Worker-7] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session C2B7B812FA7BBD1BDB7C82466CE055D7 at Tue Jul 30 06:25:05 PDT 2024
2024-07-29 06:26:36.670 [quartzScheduler_Worker-8] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-6f7a7c7f-c5ab-45da-af33-9d1fe4a993af fired at Mon Jul 29 06:26:36 PDT 2024
2024-07-29 06:26:37.202 [quartzScheduler_Worker-8] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session FD23913CF1A3F6E39C0941A0A6139DD9 at Tue Jul 30 06:26:27 PDT 2024
2024-07-29 06:26:53.229 [quartzScheduler_Worker-9] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-1b9ad6ba-1875-4bce-91e3-8ed3484c3ece fired at Mon Jul 29 06:26:53 PDT 2024
2024-07-29 06:26:53.582 [quartzScheduler_Worker-9] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session D84DF214A78FC5F695DAC38D71AD33DE at Tue Jul 30 06:26:43 PDT 2024
2024-07-29 06:29:00.810 [quartzScheduler_Worker-10] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-fb81b46d-0d4b-46ef-a633-0ccafd14c9fc fired at Mon Jul 29 06:29:00 PDT 2024
2024-07-29 06:29:01.259 [quartzScheduler_Worker-10] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session BDFD972DF69C39A1310EA1EB328DDCCB at Tue Jul 30 06:28:51 PDT 2024
2024-07-29 06:29:31.898 [quartzScheduler_Worker-1] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-e9015357-065f-44f2-826c-680c6c71c446 fired at Mon Jul 29 06:29:31 PDT 2024
2024-07-29 06:29:32.292 [quartzScheduler_Worker-1] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session C8571B1B432D456231AED0F7387C7CAC at Tue Jul 30 06:29:22 PDT 2024
2024-07-29 06:30:32.015 [quartzScheduler_Worker-3] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-b61a0b82-3d22-47c1-abe5-342ceb6acef8 fired at Mon Jul 29 06:30:32 PDT 2024
2024-07-29 06:30:32.433 [quartzScheduler_Worker-3] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session A0BBF496C7319C83C954B59B1051E607 at Tue Jul 30 06:30:22 PDT 2024
2024-07-29 06:31:15.510 [quartzScheduler_Worker-2] INFO  e.o.c.c.model.omron.RefreshTokenJob [RefreshTokenJob.java:27] running job refreshTokenJob-dbecfad6-cea6-4a4d-903a-7d2c1d6e9d78 fired at Mon Jul 29 06:31:15 PDT 2024
```

This is weird.  All of these sessions shouldn't exist like this.

It may well be the case that this is indicative of sessions not getting cleared correctly, which, if that were the case, could explain the _OutOfMemoryError_ - sessions aren't expiring as they should, which means their _UserWorkspace_ objects persist, which are full of all sorts of working data, which consumes a lot of space, causing token refresh jobs to continue, and memory to fill.

Dig into this.

**Comment by mattStorer** [comment]
It also appears that perhaps multiple Omron token refresh jobs may be scheduled for the same _sessionId_.  Take, for example, these logs, which show two token refresh jobs occurring for the same _sessionId_:

```
coach.2024-07-27.log:2024-07-27 06:24:12.764 [http-nio-50000-exec-14] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session BDFD972DF69C39A1310EA1EB328DDCCB at Sun Jul 28 06:24:02 PDT 2024
coach.2024-07-27.log:2024-07-27 06:29:20.429 [http-nio-50000-exec-21] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session BDFD972DF69C39A1310EA1EB328DDCCB at Sun Jul 28 06:29:10 PDT 2024
coach.2024-07-28.log:2024-07-28 06:24:03.170 [quartzScheduler_Worker-8] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session BDFD972DF69C39A1310EA1EB328DDCCB at Mon Jul 29 06:23:53 PDT 2024
coach.2024-07-28.log:2024-07-28 06:29:10.810 [quartzScheduler_Worker-2] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session BDFD972DF69C39A1310EA1EB328DDCCB at Mon Jul 29 06:29:00 PDT 2024
coach.2024-07-29.log:2024-07-29 06:23:53.530 [quartzScheduler_Worker-6] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session BDFD972DF69C39A1310EA1EB328DDCCB at Tue Jul 30 06:23:43 PDT 2024
coach.2024-07-29.log:2024-07-29 06:29:01.259 [quartzScheduler_Worker-10] INFO  e.o.cmp.coach.service.OmronService [OmronService.java:260] scheduling Omron token refresh for session BDFD972DF69C39A1310EA1EB328DDCCB at Tue Jul 30 06:28:51 PDT 2024
```

It looks like the tokens expire after 24 hours, as the jobs are designed to refresh 10 seconds before they expire.  So there are two sets of jobs above, each offset by 5 minutes, and refreshing 24 hours - 10 seconds later.  This shouldn't happen.

This probably happened by the associated user syncing with Omron, and then syncing again 5 minutes later.

**Augment the token fresh logic to ensure that there can exist only one refresh job per sessionId**

This is a minor thing though, in the grand scheme - refreshing a token twice in a few minutes won't impact the system the way backend _UserWorkspace_ objects persisting indefinitely will cause.

**Comment by mattStorer** [comment]
added some code to check to make sure that workspaces get shut down and expunged in a reasonable amount of time after their respective access token has expired.  also added additional logging to help trap information about how many workspaces are registered, and how many remain, at the beginning and end of this housekeeping process.  if my assessment regarding the cause of this _OutOfMemoryError_ issue is correct, I believe these changes should resolve this issue.
